language: python

python:
  - "3.6"

services:
  - postgresql

before_script:
  - psql -c 'create database questioner_test;' -U postgres

install:
  - pip install -r requirements.txt

script:

  - python -m pytest --cov

after_success:
- coveralls